// @program: hello-students
// @author: edte
// @create: 2020-08-10 18:51
package service

// CollegeForm
type CollegeForm struct {
	Region string `form:"region" binding:"required"`
	Name   string `form:"name" binding:"required"`
}

var majorToCollege = map[string]string{
	"电子信息类（通信与信息类）":   "通信与信息工程学院",
	"数字媒体技术":          "通信与信息工程学院",
	"计算机类（计算机与智能科学类）": "计算机科学与技术学院/人工智能学院",
	"自动化类（自动化与电气工程类）": "自动化学院",
	"机械类（智能制造与机器人类）":  "先进制造工程学院",
	"电子信息类（电子工程类）":    "光电工程学院/重庆国际半导体学院",
	"电子信息类（集成电路工程类）":  "光电工程学院/重庆国际半导体学院",
	"生物医学工程":          "生物信息学院",
	"生物信息学":           "生物信息学院",
	"医学信息工程":          "生物信息学院",
	"数学类（数学与信息科学类）":   "理学院",
	"应用物理学":           "理学院",
	"工商管理类":           "经济管理学院",
	"经济学类（经济金融类）":     "经济管理学院",
	"信息管理与信息系统":       "经济管理学院",
	"工程管理":            "经济管理学院",
	"电子商务类":           "现代邮政学院",
	"邮政工程":            "现代邮政学院",
	"法学类":             "网络空间安全与信息法学院",
	"计算机类（网络安全类）":     "网络空间安全与信息法学院",
	"外国语言文学类":         "外国语学院",
	"电子信息工程（中外合作办学）":  "国际学院",
	"通信工程（中外合作办学）":    "国际学院",
	"软件工程（中外合作办学）":    "国际学院",
	"软件工程":            "软件工程学院",
	"广播电视编导":          "传媒艺术学院",
	"设计学类（数字媒体与动画类）":  "传媒艺术学院",
	"设计学类（艺术设计类）":     "传媒艺术学院",
	"社会体育指导与管理":       "体育学院",
}

type collegeData struct {
	regions      map[string]int
	number       int
	majors       []string
	majorNumber  int
	introduction string
	sexRatio     string
}

var college = map[string]collegeData{
	"体育学院": {
		regions: map[string]int{
			"安徽": 3,
			"贵州": 4,
			"河南": 3,
			"湖北": 3,
			"湖南": 3,
			"山东": 3,
			"四川": 4,
			"重庆": 37,
		},
		number:       60,
		majors:       []string{"社会体育指导与管理"},
		majorNumber:  1,
		introduction: "学院毕业生平均就业率达到95%以上。毕业生就业分布在体育、教育、通信等行业。",
		sexRatio:     "9:1",
	},
	"通信与信息工程学院": {
		regions: map[string]int{
			"安徽":  14,
			"北京":  3,
			"福建":  5,
			"甘肃":  4,
			"广东":  14,
			"广西":  6,
			"贵州":  8,
			"海南":  3,
			"河北":  10,
			"河南":  16,
			"黑龙江": 2,
			"湖北":  16,
			"湖南":  13,
			"吉林":  3,
			"江苏":  8,
			"江西":  9,
			"辽宁":  3,
			"内蒙古": 3,
			"宁夏":  7,
			"青海":  4,
			"山东":  12,
			"山西":  8,
			"陕西":  14,
			"上海":  4,
			"四川":  24,
			"天津":  3,
			"西藏":  2,
			"新疆":  6,
			"云南":  11,
			"浙江":  6,
			"重庆":  269,
		},
		number:       510,
		majors:       []string{"数字媒体技术", "通信工程", "电子信息工程", "信息工程"},
		majorNumber:  4,
		introduction: "是拥有国家级实验教学示范中心、国家级虚拟仿真实验中心、国家级特色专业的学院",
		sexRatio:     "8:2",
	},
	"传媒艺术学院": {
		regions: map[string]int{
			"安徽": 16,
			"甘肃": 7,
			"广东": 9,
			"广西": 12,
			"贵州": 12,
			"河北": 10,
			"湖北": 18,
			"湖南": 18,
			"山东": 18,
			"山西": 11,
			"四川": 16,
			"重庆": 191,
		},
		number:       370,
		majors:       []string{"广播电视编导", "动画", "数字媒体艺术", "视觉传达设计", "环境设计", "产品设计"},
		majorNumber:  3,
		introduction: "学院具有集教学、实践、科研于一体的传媒艺术大楼、26个数字艺术专业实验室。",
		sexRatio:     "2:8",
	},
	"软件工程学院": {
		regions: map[string]int{
			"安徽": 10,
			"广西": 10,
			"贵州": 12,
			"河北": 5,
			"河南": 10,
			"江西": 10,
			"山东": 14,
			"山西": 10,
			"四川": 65,
			"云南": 12,
			"重庆": 331,
		},
		number:       479,
		majors:       []string{"软件工程"},
		majorNumber:  1,
		introduction: "软件工程专业是国家首批一流专业、国家级特色专业、教育部卓越工程师计划专业。",
		sexRatio:     "8:2",
	},
	"国际学院": {
		regions: map[string]int{
			"安徽": 28,
			"福建": 10,
			"广东": 10,
			"河北": 25,
			"河南": 10,
			"湖北": 10,
			"湖南": 10,
			"江西": 10,
			"山东": 27,
			"四川": 65,
			"重庆": 95,
		},
		number:       300,
		majors:       []string{"软件工程（中外合作办学）", "通信工程（中外合作办学）", "电子信息工程（中外合作办学）"},
		majorNumber:  3,
		introduction: "学院是学校实施国际化战略的重要平台，是执行国际教育任务的管理与教学单位",
		sexRatio:     "8:2",
	},
	"外国语学院": {
		regions: map[string]int{
			"安徽": 4,
			"广东": 2,
			"河北": 2,
			"河南": 4,
			"湖北": 4,
			"湖南": 2,
			"吉林": 2,
			"江苏": 4,
			"辽宁": 3,
			"四川": 2,
			"重庆": 34,
		},
		number:       60,
		majors:       []string{"英语专业", "翻译专业"},
		majorNumber:  2,
		introduction: "学院三分之二以上教师有国外进修或留学经历，常年聘请高水平外教数名",
		sexRatio:     "2:8",
	},
	"网络空间安全与信息法学院": {
		regions: map[string]int{
			"安徽": 5,
			"甘肃": 4,
			"广东": 5,
			"贵州": 5,
			"河北": 7,
			"湖北": 11,
			"湖南": 10,
			"江西": 4,
			"辽宁": 3,
			"宁夏": 6,
			"山东": 8,
			"山西": 4,
			"陕西": 8,
			"四川": 27,
			"云南": 3,
			"重庆": 170,
		},
		number:       280,
		majors:       []string{"法学", "知识产权", "信息安全", "网络空间安全"},
		majorNumber:  4,
		introduction: "是具有1个重庆市特色专业、2个重庆市“十三五”重点学科的学院",
		sexRatio:     "7:3",
	},
	"现代邮政学院": {
		regions: map[string]int{
			"安徽": 5,
			"福建": 2,
			"甘肃": 2,
			"广东": 6,
			"贵州": 6,
			"河北": 4,
			"河南": 2,
			"湖北": 4,
			"湖南": 2,
			"江苏": 6,
			"山东": 3,
			"山西": 2,
			"陕西": 8,
			"四川": 11,
			"新疆": 4,
			"云南": 5,
			"浙江": 6,
			"重庆": 48,
		},
		number:       120,
		majors:       []string{"电子商务", "物流管理", "邮政工程"},
		majorNumber:  3,
		introduction: "学院由重庆市人民政府和国家邮政局挂牌并共建，是全国首批成立的四个现代邮政学院之一",
		sexRatio:     "6:4",
	},
	"经济管理学院": {
		regions: map[string]int{
			"安徽":  12,
			"福建":  8,
			"甘肃":  7,
			"广东":  14,
			"贵州":  3,
			"海南":  4,
			"河北":  5,
			"河南":  5,
			"黑龙江": 4,
			"湖北":  7,
			"湖南":  4,
			"吉林":  2,
			"江苏":  9,
			"辽宁":  2,
			"宁夏":  7,
			"青海":  2,
			"山东":  8,
			"山西":  7,
			"陕西":  6,
			"上海":  4,
			"四川":  11,
			"天津":  2,
			"西藏":  3,
			"新疆":  8,
			"云南":  6,
			"浙江":  4,
			"重庆":  266,
		},
		number:       420,
		majors:       []string{"市场营销", "会计学", "信息管理与信息系统", "工程管理", "经济学", "金融工程", "工商管理"},
		majorNumber:  7,
		introduction: "是拥有1个省部级重点学科、2个硕士点、4个省部级研究基地的学院",
		sexRatio:     "6:4",
	},
	"理学院": {
		regions: map[string]int{
			"安徽": 5,
			"福建": 3,
			"甘肃": 5,
			"广东": 3,
			"贵州": 3,
			"海南": 2,
			"河北": 3,
			"河南": 5,
			"湖北": 5,
			"湖南": 5,
			"江苏": 3,
			"江西": 5,
			"宁夏": 2,
			"青海": 2,
			"山东": 3,
			"山西": 3,
			"陕西": 3,
			"四川": 5,
			"云南": 4,
			"重庆": 92,
		},
		number:       161,
		majors:       []string{"信息与计算科学", "数学与应用数学", "应用物理学", "数据计算及应用"},
		majorNumber:  4,
		introduction: "是拥有1个省部级重点学科、1个重庆市特色专业、3个省部级重点实验室的学院",
		sexRatio:     "7:3",
	},
	"生物信息学院": {
		regions: map[string]int{
			"安徽":  6,
			"福建":  2,
			"广东":  6,
			"广西":  3,
			"贵州":  5,
			"海南":  2,
			"河北":  8,
			"河南":  4,
			"黑龙江": 4,
			"湖北":  8,
			"湖南":  4,
			"吉林":  6,
			"辽宁":  5,
			"宁夏":  3,
			"山东":  5,
			"山西":  7,
			"陕西":  8,
			"四川":  10,
			"新疆":  4,
			"云南":  4,
			"重庆":  156,
		},
		number:       260,
		majors:       []string{"生物信息学", "生物医学工程", "医学信息工程"},
		majorNumber:  3,
		introduction: "是培养信息技术在医疗装备、健康信息、生物大数据等领域中应用的高级专门人才的学院",
		sexRatio:     "7:3",
	},
	"光电工程学院/重庆国际半导体学院": {
		regions: map[string]int{
			"安徽":  9,
			"福建":  7,
			"甘肃":  7,
			"广东":  16,
			"广西":  10,
			"贵州":  12,
			"海南":  7,
			"河北":  12,
			"河南":  16,
			"黑龙江": 2,
			"湖北":  12,
			"湖南":  12,
			"吉林":  2,
			"江西":  12,
			"辽宁":  6,
			"宁夏":  8,
			"青海":  2,
			"山东":  14,
			"山西":  9,
			"陕西":  16,
			"四川":  32,
			"新疆":  6,
			"云南":  18,
			"浙江":  12,
			"重庆":  321,
		},
		number:       580,
		majors:       []string{"光电信息科学与技术", "电子科学与技术", "电磁场与无线技术", "微电子科学与工程", "电子信息科学与技术", "集成电路设计与集成系统"},
		majorNumber:  6,
		introduction: "学院具有一个国家一流本科专业、一个国家级特色专业、长江学者、国家特聘专家级别的教师。",
		sexRatio:     "8:2",
	},
	"先进制造工程学院": {
		regions: map[string]int{
			"安徽":  6,
			"福建":  3,
			"广东":  10,
			"广西":  2,
			"海南":  5,
			"河北":  6,
			"河南":  6,
			"黑龙江": 2,
			"湖北":  10,
			"湖南":  9,
			"江苏":  6,
			"江西":  8,
			"内蒙古": 2,
			"青海":  4,
			"山东":  10,
			"山西":  8,
			"陕西":  8,
			"四川":  20,
			"新疆":  6,
			"云南":  10,
			"重庆":  185,
		},
		number:       330,
		majors:       []string{"机械设计制造及其自动化", "机械电子工程", "机器人工程", "智能制造工程"},
		majorNumber:  4,
		introduction: "是拥有“机械工程”重庆市重点学科；机械工程一级学科硕士点、工业工程与管理专业硕士点的学院",
		sexRatio:     "9:1",
	},

	"自动化学院": {
		regions: map[string]int{
			"安徽":  8,
			"福建":  5,
			"甘肃":  5,
			"广东":  10,
			"广西":  6,
			"贵州":  12,
			"海南":  5,
			"河北":  6,
			"河南":  17,
			"黑龙江": 3,
			"湖北":  16,
			"湖南":  16,
			"吉林":  2,
			"江苏":  8,
			"江西":  10,
			"辽宁":  3,
			"内蒙古": 3,
			"宁夏":  8,
			"山东":  10,
			"山西":  8,
			"陕西":  18,
			"四川":  30,
			"新疆":  8,
			"云南":  16,
			"浙江":  11,
			"重庆":  326,
		},
		number:       570,
		majors:       []string{"自动化", "电气工程及其自动化", "物联网工程", "智能电网信息工程", "测控技术与仪器", "机器人工程专业"},
		majorNumber:  6,
		introduction: "是拥有一支以国家级、省部级人才为核心的高水平师资队伍的学院也是科研实力最强的学院之一",
		sexRatio:     "8:2",
	},

	"计算机科学与技术学院/人工智能学院": {
		regions: map[string]int{
			"安徽":  8,
			"北京":  3,
			"福建":  5,
			"甘肃":  4,
			"广东":  15,
			"广西":  6,
			"贵州":  8,
			"海南":  5,
			"河北":  5,
			"河南":  22,
			"黑龙江": 3,
			"湖北":  26,
			"湖南":  12,
			"吉林":  3,
			"江苏":  6,
			"江西":  10,
			"辽宁":  3,
			"内蒙古": 2,
			"宁夏":  6,
			"青海":  5,
			"山东":  10,
			"山西":  8,
			"陕西":  16,
			"四川":  30,
			"天津":  3,
			"新疆":  8,
			"云南":  16,
			"浙江":  11,
			"重庆":  341,
		},
		number:       600,
		majors:       []string{"计算机科学与技术", "网络工程", "智能科学与技术", "数据科学与大数据技术", "人工智能"},
		majorNumber:  5,
		introduction: "是拥有国家级特色专业、国家级一流专业、国家级教学团队的学院",
		sexRatio:     "8:2",
	},
}

// GetCollegeNumber
func GetCollegeNumber(collegeName string) int {
	return college[collegeName].number
}

// GetCollegeName
func GetCollegeName(majorName string) string {
	return majorToCollege[majorName]
}

// GetCollegeRegionNumber
func GetCollegeRegionNumber(collegeName string, regionName string) int {
	return college[collegeName].regions[regionName]
}

// GetCollegeMajors
func GetCollegeMajors(collegeName string) []string {
	return college[collegeName].majors
}

// GetCollegeMajorNumber
func GetCollegeMajorNumber(collegeName string) int {
	return college[collegeName].majorNumber
}

// GetCollegeIntroduction
func GetCollegeIntroduction(collegeName string) string {
	return college[collegeName].introduction
}

// GetCollegeSexRatio
func GetCollegeSexRatio(collegeName string) string {
	return college[collegeName].sexRatio
}
